global:
  containerRegistry:
    path: eu.gcr.io/kyma-project
  istio:
    gateway:
      name: kyma-gateway
  service_binding_usage_controller:
    dir:
    version: "a8a6bca9"
  ingress:
    domainName: "TBD"
