---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.serviceAccountName" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "controller.clusterRoleName" . }}
rules:
  - apiGroups:
      - eventing.kyma-project.io
    resources:
      - subscriptions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.kyma-project.io
    resources:
      - subscriptions/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "controller.serviceAccountName" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "controller.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
